[package]
name = "rc2d2"
version = "0.1.0"
authors = ["jacob"]
edition = "2018"

[lib]
name = "rc2d2"
crate-type = ["cdylib"]

[dependencies]
pleco = "0.5.0"
cpython = { version = "0.5", features = ["extension-module"] }
